/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  UseInfiniteQueryOptions,
  QueryFunction,
  UseQueryResult,
  UseInfiniteQueryResult,
  QueryKey,
} from '@tanstack/react-query';
import type { GetAllKinds200Item } from '.././types';
import { axiosInstance } from '../../../axios-instance';
import type { ErrorType } from '../../../axios-instance';

/**
 * @summary 음식 종류 리스트 반환
 */
export const getAllKinds = (signal?: AbortSignal) => {
  return axiosInstance<GetAllKinds200Item[]>({ url: `/kinds`, method: 'get', signal });
};

export const getGetAllKindsQueryKey = () => [`/kinds`];

export type GetAllKindsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getAllKinds>>>;
export type GetAllKindsInfiniteQueryError = ErrorType<unknown>;

export const useGetAllKindsInfinite = <
  TData = Awaited<ReturnType<typeof getAllKinds>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAllKinds>>, TError, TData>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllKindsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllKinds>>> = ({ signal }) => getAllKinds(signal);

  const query = useInfiniteQuery<Awaited<ReturnType<typeof getAllKinds>>, TError, TData>({
    queryKey,
    queryFn,
    ...queryOptions,
  }) as UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};

export type GetAllKindsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllKinds>>>;
export type GetAllKindsQueryError = ErrorType<unknown>;

export const useGetAllKinds = <TData = Awaited<ReturnType<typeof getAllKinds>>, TError = ErrorType<unknown>>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getAllKinds>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllKindsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllKinds>>> = ({ signal }) => getAllKinds(signal);

  const query = useQuery<Awaited<ReturnType<typeof getAllKinds>>, TError, TData>({
    queryKey,
    queryFn,
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};
