/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  UseInfiniteQueryOptions,
  QueryFunction,
  UseQueryResult,
  UseInfiniteQueryResult,
  QueryKey,
} from '@tanstack/react-query';
import type { CursorPostSimple, GetPostsParams, PostDetail } from '.././types';
import { axiosInstance } from '../../../axios-instance';
import type { ErrorType } from '../../../axios-instance';

/**
 * [3km 이내 거리 가게 글만 추출]<br/>[검색어(search) : 제목, 글 내용, 음식 종류에 대한 사용자의 검색어]<br/>[정렬(sort) : DISTANCE, ORDER, STAR, REVIEW]<br/>[음식 종류(FoodType) : 전체, 치킨, 피자, 햄버거, 족발\_보쌈, 분식, 카페\_디저트, 샐러드\_샌드위치, 도시락, 한식, 중식, 일식, 그외]
 * @summary 근처 가게 글 리스트 반환
 */
export const getPosts = (params?: GetPostsParams, signal?: AbortSignal) => {
  return axiosInstance<CursorPostSimple>({ url: `/posts`, method: 'get', params, signal });
};

export const getGetPostsQueryKey = (params?: GetPostsParams) => [`/posts`, ...(params ? [params] : [])];

export type GetPostsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>;
export type GetPostsInfiniteQueryError = ErrorType<unknown>;

export const useGetPostsInfinite = <TData = Awaited<ReturnType<typeof getPosts>>, TError = ErrorType<unknown>>(
  params?: GetPostsParams,
  options?: { query?: UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData> },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({ signal }) => getPosts(params, signal);

  const query = useInfiniteQuery<Awaited<ReturnType<typeof getPosts>>, TError, TData>({
    queryKey,
    queryFn,
    ...queryOptions,
  }) as UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};

export type GetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>;
export type GetPostsQueryError = ErrorType<unknown>;

export const useGetPosts = <TData = Awaited<ReturnType<typeof getPosts>>, TError = ErrorType<unknown>>(
  params?: GetPostsParams,
  options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData> },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({ signal }) => getPosts(params, signal);

  const query = useQuery<Awaited<ReturnType<typeof getPosts>>, TError, TData>({
    queryKey,
    queryFn,
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};

/**
 * @summary 가게 글 상세 정보 반환
 */
export const getPostDetail = (postId: number, signal?: AbortSignal) => {
  return axiosInstance<PostDetail>({ url: `/posts/${postId}/info`, method: 'get', signal });
};

export const getGetPostDetailQueryKey = (postId: number) => [`/posts/${postId}/info`];

export type GetPostDetailInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPostDetail>>>;
export type GetPostDetailInfiniteQueryError = ErrorType<unknown>;

export const useGetPostDetailInfinite = <
  TData = Awaited<ReturnType<typeof getPostDetail>>,
  TError = ErrorType<unknown>,
>(
  postId: number,
  options?: { query?: UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData> },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostDetailQueryKey(postId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostDetail>>> = ({ signal }) =>
    getPostDetail(postId, signal);

  const query = useInfiniteQuery<Awaited<ReturnType<typeof getPostDetail>>, TError, TData>({
    queryKey,
    queryFn,
    enabled: !!postId,
    ...queryOptions,
  }) as UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};

export type GetPostDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getPostDetail>>>;
export type GetPostDetailQueryError = ErrorType<unknown>;

export const useGetPostDetail = <TData = Awaited<ReturnType<typeof getPostDetail>>, TError = ErrorType<unknown>>(
  postId: number,
  options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof getPostDetail>>, TError, TData> },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostDetailQueryKey(postId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostDetail>>> = ({ signal }) =>
    getPostDetail(postId, signal);

  const query = useQuery<Awaited<ReturnType<typeof getPostDetail>>, TError, TData>({
    queryKey,
    queryFn,
    enabled: !!postId,
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};
