/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export type BannerInfoType = (typeof BannerInfoType)[keyof typeof BannerInfoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BannerInfoType = {
  NOTICE: 'NOTICE',
  EVENT: 'EVENT',
} as const;
