/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { BigItemResp } from './bigItemResp';

export interface BigCategoryResp {
  id?: number;
  bigCategory?: string;
  bigItems?: BigItemResp[];
}
