/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface BigItemResp {
  id?: number;
  bigItem?: string;
  description?: string;
  price?: number;
  image?: string;
  isExhausted?: boolean;
}
