/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface CouponSimple {
  id?: number;
  couponNo?: string;
  name?: string;
  isFixed?: boolean;
  amount?: number;
  minPrice?: number;
  expiration?: string;
  storeId?: number;
}
