/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface EventSimple {
  id?: number;
  title?: string;
  banner?: string;
  pub?: boolean;
  start?: string;
  end?: string;
}
