/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export type GetAllKinds200Item = (typeof GetAllKinds200Item)[keyof typeof GetAllKinds200Item];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAllKinds200Item = {
  치킨: '치킨',
  분식: '분식',
  한식: '한식',
  일식: '일식',
  중식: '중식',
  카페_디저트: '카페_디저트',
  피자: '피자',
  햄버거: '햄버거',
  족발_보쌈: '족발_보쌈',
  샐러드_샌드위치: '샐러드_샌드위치',
  도시락: '도시락',
  전체: '전체',
  그외: '그외',
} as const;
