/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { ZoneCursorReq } from './zoneCursorReq';

export type GetNearlyZonesParams = {
  lng: number;
  lat: number;
  reqDto?: ZoneCursorReq;
};
