/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPostsFoodType } from './getPostsFoodType';
import type { GetPostsSort } from './getPostsSort';

export type GetPostsParams = {
  /**
   * 기본값 : 빈문자열
   */
  search?: string;
  /**
   * 기본값 : 전체
   */
  foodType?: GetPostsFoodType;
  /**
   * 기본값 : DISTANCE
   */
  sort?: GetPostsSort;
  /**
   * 기본값 : 0
   */
  lastId?: number;
};
