/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export type GetPostsSort = (typeof GetPostsSort)[keyof typeof GetPostsSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPostsSort = {
  DISTANCE: 'DISTANCE',
  ORDER: 'ORDER',
  STAR: 'STAR',
  REVIEW: 'REVIEW',
} as const;
