/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { GetStoreReviewsSort } from './getStoreReviewsSort';

export type GetStoreReviewsParams = {
  storeId: number;
  /**
   * 기본값 : NEWER
   */
  sort?: GetStoreReviewsSort;
  /**
   * 기본값 : false
   */
  hasImage?: boolean;
  /**
   * 기본값 : 0
   */
  lastId?: number;
};
