/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from './address';

export interface LocationDetail {
  id?: number;
  alias?: string;
  isActive?: boolean;
  address?: Address;
}
