/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { OrderSimpleStatus } from './orderSimpleStatus';

export interface OrderSimple {
  orderNo?: string;
  storeName?: string;
  simpleMenu?: string;
  finalPrice?: number;
  requirements?: string;
  status?: OrderSimpleStatus;
  pickUpAt?: string;
}
