/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export type OrderRespForPayStatus = (typeof OrderRespForPayStatus)[keyof typeof OrderRespForPayStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderRespForPayStatus = {
  PRE_PAY: 'PRE_PAY',
  PAY_READY: 'PAY_READY',
  PAY_CANCEL: 'PAY_CANCEL',
  PAY_FAIL: 'PAY_FAIL',
  REQUEST: 'REQUEST',
  ACCEPT: 'ACCEPT',
  REFUSE: 'REFUSE',
  USER_CANCEL: 'USER_CANCEL',
  STORE_CANCEL: 'STORE_CANCEL',
  DONE: 'DONE',
  SYSTEM_DONE: 'SYSTEM_DONE',
  SYSTEM_CANCEL: 'SYSTEM_CANCEL',
  ISSUE: 'ISSUE',
} as const;
