/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { OrderListRespStatus } from './orderListRespStatus';

export interface OrderListResp {
  id?: number;
  orderNo?: string;
  storeId?: number;
  orderAt?: string;
  storeProfile?: string;
  storeName?: string;
  simpleMenu?: string;
  finalPrice?: number;
  pickUpAt?: string;
  acceptAt?: string;
  doneAt?: string;
  status?: OrderListRespStatus;
  isReviewed?: boolean;
}
