/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface OrderDoneResp {
  id?: number;
  finalPrice?: number;
  distance?: number;
  stepCount?: number;
  maxRewardRatio?: number;
  maxRewardDistance?: number;
  reward?: number;
}
