/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { Coordinate } from './coordinate';
import type { CreateCartReq } from './createCartReq';

export interface OrderCreateReq {
  couponNo?: string;
  requirements?: string;
  usePoint?: number;
  afterMin?: number;
  coordinate?: Coordinate;
  storeId?: number;
  cartInfo?: CreateCartReq;
  finalPrice?: number;
}
