/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export type PayCreateReqMethod = (typeof PayCreateReqMethod)[keyof typeof PayCreateReqMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PayCreateReqMethod = {
  CARD: 'CARD',
} as const;
