/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { PayScreenUrl } from './payScreenUrl';

export interface PaymentDto {
  version?: string;
  paymentKey?: string;
  type?: string;
  orderName?: string;
  currency?: string;
  method?: string;
  totalAmount?: number;
  balanceAmount?: number;
  status?: string;
  requestedAt?: string;
  approvedAt?: string;
  useEscrow?: boolean;
  lastTransactionKey?: string;
  suppliedAmount?: number;
  vat?: number;
  cultureExpense?: boolean;
  taxFreeAmount?: number;
  taxExemptionAmount?: number;
  checkout?: PayScreenUrl;
  mid?: string;
  orderId?: string;
}
