/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface PostSimple {
  id?: number;
  postTitle?: string;
  minCookTime?: number;
  storeName?: string;
  storeProfile?: string;
  star?: number;
  orderCount?: number;
  reviewCount?: number;
  town?: string;
  distance?: number;
  foodTypes?: string[];
}
