/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { PostCursorReqFoodType } from './postCursorReqFoodType';
import type { PostCursorReqSort } from './postCursorReqSort';

export interface PostCursorReq {
  search?: string;
  foodType?: PostCursorReqFoodType;
  sort?: PostCursorReqSort;
  lastId?: number;
}
