/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export type PostCursorReqSort = (typeof PostCursorReqSort)[keyof typeof PostCursorReqSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCursorReqSort = {
  DISTANCE: 'DISTANCE',
  ORDER: 'ORDER',
  STAR: 'STAR',
  REVIEW: 'REVIEW',
} as const;
