/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface PostDetail {
  storeImages?: string[];
  storeName?: string;
  storeStar?: number;
  reviewCount?: number;
  orderCount?: number;
  postTitle?: string;
  minCookTime?: number;
  storeAddress?: string;
  storePhone?: string;
  postContent?: string;
  isPicked?: boolean;
}
