/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface ReviewResp {
  id?: number;
  userProfile?: string;
  userNickname?: string;
  reviewStar?: number;
  reviewComment?: string;
  reviewImages?: string[];
  reviewCreatedDate?: string;
  reply?: string;
  replyCreatedDate?: string;
}
