/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface ReviewWriteReq {
  orderNo?: string;
  star?: number;
  comment?: string;
  images?: string[];
}
