/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export type ReviewCursorReqSortBy = (typeof ReviewCursorReqSortBy)[keyof typeof ReviewCursorReqSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewCursorReqSortBy = {
  NEWER: 'NEWER',
  STAR_HIGH: 'STAR_HIGH',
  STAR_LOW: 'STAR_LOW',
} as const;
