/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { SmallItemResp } from './smallItemResp';

export interface SmallCategoryResp {
  id?: number;
  smallCategory?: string;
  checkLimit?: number;
  smallItems?: SmallItemResp[];
}
