/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface StorePolicyTerms {
  agreePolicy1?: boolean;
  agreePolicy2?: boolean;
  agreePolicy3?: boolean;
}
