/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { StoreJoinReqFoodTypesItem } from './storeJoinReqFoodTypesItem';
import type { MasterInfo } from './masterInfo';
import type { StorePolicyTerms } from './storePolicyTerms';
import type { Address } from './address';

export interface StoreJoinReq {
  name?: string;
  license?: string;
  phone?: string;
  foodTypes?: StoreJoinReqFoodTypesItem[];
  maxRewardRatio?: number;
  minCookTime?: number;
  loginId?: string;
  loginPwd?: string;
  masterInfo?: MasterInfo;
  storePolicyTerms?: StorePolicyTerms;
  address?: Address;
  profile?: string;
  images?: string[];
}
