/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import type { Psu } from './psu';

export interface StoreJoinResp {
  storeId?: number;
  profile?: Psu;
  images?: Psu[];
}
