/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */

export interface UserSimple {
  nickname?: string;
  profile?: string;
  point?: number;
  town?: string;
}
