/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Leg User API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  UseInfiniteQueryOptions,
  QueryFunction,
  UseQueryResult,
  UseInfiniteQueryResult,
  QueryKey,
} from '@tanstack/react-query';
import type { BannerSimple } from '.././types';
import { axiosInstance } from '../../../axios-instance';
import type { ErrorType } from '../../../axios-instance';

/**
 * @summary 배너 목록 조회
 */
export const getBannerList = (signal?: AbortSignal) => {
  return axiosInstance<BannerSimple[]>({ url: `/banners`, method: 'get', signal });
};

export const getGetBannerListQueryKey = () => [`/banners`];

export type GetBannerListInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getBannerList>>>;
export type GetBannerListInfiniteQueryError = ErrorType<unknown>;

export const useGetBannerListInfinite = <
  TData = Awaited<ReturnType<typeof getBannerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseInfiniteQueryOptions<Awaited<ReturnType<typeof getBannerList>>, TError, TData>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBannerListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBannerList>>> = ({ signal }) => getBannerList(signal);

  const query = useInfiniteQuery<Awaited<ReturnType<typeof getBannerList>>, TError, TData>({
    queryKey,
    queryFn,
    ...queryOptions,
  }) as UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};

export type GetBannerListQueryResult = NonNullable<Awaited<ReturnType<typeof getBannerList>>>;
export type GetBannerListQueryError = ErrorType<unknown>;

export const useGetBannerList = <
  TData = Awaited<ReturnType<typeof getBannerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getBannerList>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBannerListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBannerList>>> = ({ signal }) => getBannerList(signal);

  const query = useQuery<Awaited<ReturnType<typeof getBannerList>>, TError, TData>({
    queryKey,
    queryFn,
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};
